Update image_extractor.rs
FOSScope/Toolkit pull request #11
Opened 2024-07-11 01:29 UTC by cys2004

Added module "image_extractor.rs" that filters and saves images from the original article to a specified local directory based on their file extensions.

2024-07-11 01:58 UTC, Cubik65536 requested changes

2024-07-11 01:58 UTC, Cubik65536 commented on src-rust/toolkit-core/Cargo.toml
> +reqwest = { version = "0.12", features = ["json","blocking"] } # HTTP Client
```suggestion
reqwest = { version = "0.12", features = ["json", "blocking"] } # HTTP Client
```

2024-07-11 01:58 UTC, Cubik65536 commented on src-rust/toolkit-core/src/parser/image_extractor.rs
> +/*
我们同步一下全部用 `///` 样式的注释吧

2024-07-11 01:58 UTC, Cubik65536 commented on src-rust/toolkit-core/src/parser/image_extractor.rs
> +}
结尾加空行

2024-07-12 01:27 UTC, cys2004 commented on src-rust/toolkit-core/src/parser/image_extractor.rs
> +/*
OK

2024-07-12 01:31 UTC, closed without merging